//Admin Endpoint (PROTECTED)
//Protected endpoint for admin to register members
//Integrates with Prisma ORM and Supabase PostgreSQL database

import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '../[...nextauth]/route';
import { prisma } from '@/lib/prisma';
import bcrypt from 'bcrypt';

export async function POST(request) {
  try {
    // STEP 1: Validate that requester is an ADMIN
    const session = await getServerSession(authOptions);

    if (!session || session.user.role !== 'ADMIN') {
      return NextResponse.json(
        { error: 'Unauthorized. Admin access required.' },
        { status: 403 }
      );
    }

    // STEP 2: Parse request body
    const body = await request.json();
    const {
      full_name,
      email,
      phone,
      church_name,
      password,
      role = 'MEMBER',
      is_active = true,
    } = body;

    // STEP 3: Validate required fields
    if (!full_name || !email || !phone || !church_name || !password) {
      return NextResponse.json(
        { error: 'All fields are required' },
        { status: 400 }
      );
    }

    // STEP 4: Force role to MEMBER (admin cannot create other admins via this endpoint)
    const memberRole = 'MEMBER';

    // STEP 5: Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      return NextResponse.json(
        { error: 'Invalid email format' },
        { status: 400 }
      );
    }

    // STEP 6: Validate password strength
    if (password.length < 8) {
      return NextResponse.json(
        { error: 'Password must be at least 8 characters long' },
        { status: 400 }
      );
    }

    // STEP 7: Validate phone format (basic validation)
    const phoneRegex =
      /^[+]?[(]?[0-9]{1,3}[)]?[-\s.]?[(]?[0-9]{1,4}[)]?[-\s.]?[0-9]{1,4}[-\s.]?[0-9]{1,9}$/;
    if (!phoneRegex.test(phone.replace(/\s/g, ''))) {
      return NextResponse.json(
        { error: 'Invalid phone number format' },
        { status: 400 }
      );
    }

    // STEP 8: Check if email already exists
    const existingEmail = await prisma.user.findUnique({
      where: { email: email.toLowerCase() },
    });

    if (existingEmail) {
      return NextResponse.json(
        { error: 'Email already registered. Please use a different email.' },
        { status: 409 }
      );
    }

    // STEP 9: Check if phone already exists
    const existingPhone = await prisma.user.findUnique({
      where: { phone },
    });

    if (existingPhone) {
      return NextResponse.json(
        {
          error:
            'Phone number already registered. Please use a different phone number.',
        },
        { status: 409 }
      );
    }

    // STEP 10: Hash password using bcrypt
    let hashedPassword;
    try {
      hashedPassword = await bcrypt.hash(password, 10);
    } catch (hashError) {
      console.error('Password hashing error:', hashError);
      return NextResponse.json(
        { error: 'Failed to process password' },
        { status: 500 }
      );
    }

    // STEP 11: Create user in database with all required fields
    // UUID is auto-generated by Prisma with @default(uuid())
    // registration_date is set to current time
    const newUser = await prisma.user.create({
      data: {
        email: email.toLowerCase(),
        phone: phone.trim(),
        full_name: full_name.trim(),
        church_name: church_name.trim(),
        password: hashedPassword,
        role: memberRole,
        registration_date: new Date(),
        is_active: is_active || true,
      },
      select: {
        id: true,
        email: true,
        phone: true,
        full_name: true,
        church_name: true,
        role: true,
        registration_date: true,
        is_active: true,
        created_at: true,
        updated_at: true,
      },
    });

    // STEP 12: Return success response with complete user data
    return NextResponse.json(
      {
        message: 'Member registered successfully',
        user: newUser,
      },
      { status: 201 }
    );
  } catch (error) {
    console.error('Registration error:', error);

    // Handle specific Prisma errors
    if (error.code === 'P2002') {
      const field = error.meta?.target?.[0] || 'field';
      return NextResponse.json(
        { error: `${field} already exists. Please use a different value.` },
        { status: 409 }
      );
    }

    // Handle database connection errors
    if (error.code === 'ECONNREFUSED' || error.code === 'P1000') {
      return NextResponse.json(
        {
          error: 'Database connection failed. Please try again later.',
        },
        { status: 503 }
      );
    }

    return NextResponse.json(
      { error: 'Internal server error. Please try again later.' },
      { status: 500 }
    );
  }
}
